feat: extra pixels eraser
keep-starknet-strange/art-peace pull request #139
Opened 2024-05-07 10:12 UTC by EjembiEmmanuel

- [x] issue #101
- [x] follows contribution [guide](https://github.com/keep-starknet-strange/art-peace/blob/main/CONTRIBUTING.md)
- [] code change includes tests
- [] breaking change

This PR implements a feature for erasing extra pixels from the canvas

2024-05-07 14:31 UTC, b-j-roberts requested changes
Nice work so far, very cool!

Could you have it so that selecting "Place pixel" also exits eraser mode?

2024-05-07 14:31 UTC, b-j-roberts commented on frontend/src/canvas/CanvasContainer.js
> +      const pixelIndex = props.extraPixelsData.indexOf(pixel[0]);
I think using `findIndex` instead of `filter` then `indexOf` would be best for this

2024-05-07 14:31 UTC, b-j-roberts commented on frontend/src/tabs/canvas/ExtraPixelsPanel.js
> +  // const clearExtraPixel = () => {
You can delete these lines if its not used

2024-05-07 14:31 UTC, b-j-roberts commented on frontend/src/App.js
> +    });
This might be some artifact from merging changes, but the deleted implementation is the prefered one here.

2024-05-08 04:06 UTC, b-j-roberts requested changes
Just tested it out, have a couple things:

1. Clicking into "Eraser" mode should cancel the selected color so that the color isn't following the cursor.
2. It would be nice to make it more obvious the user is in eraser mode. Maybe having the selected pixel highlighter follow the cursor in some way would be cool.

2024-05-09 19:27 UTC, b-j-roberts requested changes
One last thing then its ready to merge, good work!

2024-05-09 19:27 UTC, b-j-roberts commented on frontend/src/tabs/canvas/ExtraPixelsPanel.js
>    const submit = async () => {
Submit should exit eraser mode as well.

2024-05-13 16:43 UTC, b-j-roberts commented
Thank you! Awesome feature!

2024-05-13 16:43 UTC, merged

2024-05-13 16:47 UTC, EjembiEmmanuel commented
Thank you!