feat: quest username quest fix #130
keep-starknet-strange/art-peace pull request #160
Opened 2024-05-17 17:13 UTC by Calebux

- [ ] issue #130 
- [ ] follows contribution [guide](https://github.com/keep-starknet-strange/art-peace/blob/main/CONTRIBUTING.md)
- [ ] code change includes tests
- [ ] breaking change

Username quest that award reward if user has claim a username 

The quest contract implemented IQuest interface 
Which 
- allow for claiming of reward, 
- get claim reward 
- check a user is eligible for claim rewards

2024-05-21 02:51 UTC, b-j-roberts requested changes
Requested a few changes, if you can resolve them. Also please use `scarb fmt` for CI to pass.

2024-05-21 02:51 UTC, b-j-roberts commented on onchain/src/quests/username_quest.cairo
> +        username: felt252,
This field is unneeded.

2024-05-21 02:51 UTC, b-j-roberts commented on onchain/src/quests/username_quest.cairo
> +        pub username: felt252,
Please remove this, since it's unneeded.

2024-05-21 02:51 UTC, b-j-roberts commented on onchain/src/lib.cairo
> +    pub mod username_quest;
You'll need to add the username quests tests module to the tests section in this file too, otherwise the tests wont run.

2024-05-21 02:51 UTC, b-j-roberts commented on onchain/src/quests/username_quest.cairo
> +                return true;
If the username == 0, then there is no username. So this should return not claimable

2024-05-21 02:51 UTC, b-j-roberts commented on tests/username_quest.cairo
> +}
Please make another test using `should_panic` to check that the quest is not claimable when the user hasn't claimed a username yet.

2024-05-24 15:21 UTC, Calebux commented
this is the function am trying to test, 


```
fn is_claimable(
            self: @ContractState, user: ContractAddress, calldata: Span<felt252>
        ) -> bool {
            if self.claimed.read(user) {
                return false;
            }

            let username_store_main = IUsernameStoreDispatcher {
                contract_address: self.username_store.read()
            };

            let claim_username: felt252 = username_store_main.get_username(user);

            if claim_username == 0 {
                return false;
            }

            return true;
        }
```
this is the test a wrote, 

```
#[test]
fn username_quest_test() {
    let username_store_address = deploy_username_store_contract();
    println!("username store contract address inside test: {:?}", username_store_address);

    let username_quest_contract_address = deploy_username_quest(username_store_address);

    let art_peace = IArtPeaceDispatcher {
        contract_address: deploy_with_quests_contract(
            array![].span(), array![username_quest_contract_address].span()
        )
    };

    let username_store_dispatcher = IUsernameStoreDispatcher {
        contract_address: username_store_address
    };

    snf::start_prank(CheatTarget::One(art_peace.contract_address), utils::PLAYER1());

    username_store_dispatcher.claim_username(username);

    let initial_username = username_store_dispatcher.get_username(utils::PLAYER1());
    println!("initial username: {}", initial_username);

    println!("username address before claim_main_quest: {:?}", utils::PLAYER1());

    art_peace.claim_main_quest(0, utils::EMPTY_CALLDATA());

    println!("username address after claim_main_quest: {:?}", utils::PLAYER1());

    assert!(initial_username == username, "Username not claim after main quest ");
    snf::stop_prank(CheatTarget::One(art_peace.contract_address));
}
```


```
art_peace.claim_main_quest(0, utils::EMPTY_CALLDATA()); 

    0x5175657374206e6f7420636c61696d61626c65 ('Quest not claimable')
```

this function keep returning 0 when call from inside is_claimable


 fn get_username(self: @ContractState, address: ContractAddress) -> felt252 {
            self.user_to_username.read(get_caller_address())
        }

i suspect the user calling the function inside the test function is different from the user calling the function inside is_claimable function  @b-j-roberts @ptisserand can you help here

2024-05-24 16:06 UTC, b-j-roberts commented
What is this line returning in your example : 
`println!("initial username: {}", initial_username);`?

I think the issue is that you are pranking the art_peace contract instead of the username store contract when doing claim_username

2024-05-24 16:15 UTC, ptisserand commented
> What is this line returning in your example : `println!("initial username: {}", initial_username);`?
> 
> I think the issue is that you are pranking the art_peace contract instead of the username store contract when doing claim_username

I think the same, you have to prank both contracts:
```cairo
    snf::start_prank(CheatTarget::Multiple(array![art_peace.contract_address, username_store_address]), utils::PLAYER1());
```
instead of 
```cairo
snf::start_prank(CheatTarget::One(art_peace.contract_address), utils::PLAYER1());
```

2024-05-28 17:27 UTC, merged