feat: added a notification panel
keep-starknet-strange/art-peace pull request #193
Opened 2024-05-26 13:45 UTC by raizo07

- [x] issue https://github.com/keep-starknet-strange/art-peace/issues/182
- [x] follows contribution [guide](https://github.com/keep-starknet-strange/art-peace/blob/main/CONTRIBUTING.md)
- [x] code change includes tests

2024-06-06 14:39 UTC, b-j-roberts reviewed
I'll take a closer look soon, but in the meantime, can you remove the toastify module and code since it seems you aren't using it anymore?

2024-06-06 15:06 UTC, raizo07 commented
> I'll take a closer look soon, but in the meantime, can you remove the toastify module and code since it seems you aren't using it anymore?

@b-j-roberts Done. I've removed them.

2024-06-06 17:09 UTC, b-j-roberts commented
> @b-j-roberts Done. I've removed them.

Cool, could you revert the changes to `package-lock.json` too?

2024-06-07 00:56 UTC, b-j-roberts requested changes
Some work still needs to be done on the styling to make it match the rest of the app panels.

Also, there are changes in `frontend/package-lock.json` and `package-lock.json` that should be removed.

2024-06-07 00:56 UTC, b-j-roberts commented on frontend/src/tabs/NotificationPanel.css
> +.notification-panel {
Can you please match this to make the styling like the other panels : 
https://github.com/keep-starknet-strange/art-peace/blob/b7122c3eedf5e2be34ea392c189e8b15d4d2f84e/frontend/src/tabs/BasicTab.css#L1

2024-06-07 00:56 UTC, b-j-roberts commented on frontend/src/tabs/NotificationPanel.css
> +  .notification-content button {
There are styles here for close buttons, to make them match the style of the other panels : 
https://github.com/keep-starknet-strange/art-peace/blob/b7122c3eedf5e2be34ea392c189e8b15d4d2f84e/frontend/src/tabs/BasicTab.css#L27
https://github.com/keep-starknet-strange/art-peace/blob/b7122c3eedf5e2be34ea392c189e8b15d4d2f84e/frontend/src/utils/Styles.css#L99

2024-06-10 14:47 UTC, raizo07 commented
@b-j-roberts I've fixed them, kindly review.

2024-06-12 01:02 UTC, merged