feat: png data -> pixel data
keep-starknet-strange/art-peace pull request #58
Opened 2024-04-18 06:12 UTC by thomas192

- [x] issue #8 
- [x] follows contribution [guide](https://github.com/keep-starknet-strange/art-peace/blob/main/CONTRIBUTING.md)
- [ ] code change includes tests
- [ ] breaking change

Hey, I wanted to get this done a couple days ago, but got pulled into a few things.
First time doing Go.
I wanted to test the function, but I am not sure where it should be done. 
Let me know if changes are needed :)

2024-04-18 17:11 UTC, b-j-roberts requested changes
No worries, great work!

Yeah, there is no testing framework for the backend at the moment. And building one is kinda low priority for now, since the stakes are so low. So all good there!

2024-04-18 17:11 UTC, b-j-roberts commented on backend/routes/templates.go
> +	palette := []color.Color{
Can you load the color palette from `core.ArtPeaceBackend.CanvasConfig.Colors` and dynamically generate this array from that data?

2024-04-29 21:56 UTC, b-j-roberts commented
Hey @thomas192 , wil you be able to address the comment soon? If not, no worries, I can just merge what you have so far and have someone else work on that part.

2024-05-01 06:36 UTC, thomas192 commented
> Hey @thomas192 , wil you be able to address the comment soon? If not, no worries, I can just merge what you have so far and have someone else work on that part.

Hello Brandon, sorry my attention is elsewhere at the moment. I should have let you know.

2024-05-01 15:58 UTC, Gift-Naomi commented
Hi @b-j-roberts can you please assign me to work on this.

2024-05-01 16:00 UTC, Immanuelolivia1 commented
Hi @b-j-roberts I can handle this

2024-05-06 23:03 UTC, b-j-roberts commented
> Hello Brandon, sorry my attention is elsewhere at the moment. I should have let you know.

No worries. I can assign the rest to someone else and will reward you for the work here after it's merged.

2024-05-07 13:25 UTC, merged